map: ../maps/matfyz.osm
neural_network_file: ../555511.net
longitude: 48.1523277
latitude: 17.0711468
running_mean_weight: 0.7
# start speeding down when this far from nearest map point
speed_down_dst: 0.001
# camera/avi/jpg
#image_source: avi
#image_source: jpg
image_source: camera
# name of file to use as input instead of camera
# download example avi input from: dai.fmph.uniba.sk/projects/smelyzajko/robotour/data/example_input.avi
#image_file: ../example_input.avi
#image_file: ../example_input.jpg
image_file: none
# wheter robot is connected, offline means no comm. with robot hw
# online / offline 
#run_mode: offline
run_mode: online
